# -*- coding: utf-8 -*-
"""Ethnic Mapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vEkkQ5JmMqM-k3MxolbB1SmHh8MVq1Dn
"""

from google.colab import files
from collections import Counter
import pandas as pd
import numpy as np

upload = files.upload()

file = next(iter(upload))
df = pd.read_excel(file)

words = [word for name in df['Full Name'] for word in name.split()]

word_counts = Counter(words)

counts_df = (
    pd.DataFrame(word_counts.items(), columns = ['Word', 'Count'])
    .sort_values('Count', ascending = False)
)

counts_df.reset_index(drop = True, inplace = True)

#counts_df[320:330]

ethnicity_mapping = {
    'Chinese': {'Lee', 'Tan', 'Lim', 'Wong', 'Ng', 'Yee', 'Chin', 'Ling', 'Chan', 'Chong', 'Wei', 'Hui',
                'Yong', 'Siew', 'Chee', 'Lai', 'Leong', 'Ong', 'Hong', 'Wai', 'Mei', 'Yap', 'Kok', 'Low',
                'Goh', 'Ying', 'Chai', 'Cheng', 'Fong', 'Yi', 'Li', 'Yen', 'Liew', 'Kim', 'Ting', 'Wan',
                'Chew', 'Chen', 'Seng', 'Ho', 'Ching', 'Kong', 'Jia', 'Pei', 'Loh', 'Lau', 'Yin', 'Choo',
                'Eng', 'Heng', 'Boon', 'Mun', 'Wee', 'Wen', 'Ooi', 'Soon', 'Tee', 'Lin', 'Chua', 'Min',
                'Sim', 'Gan', 'Ang', 'Poh', 'Foo', 'Yan', 'See', 'Ming', 'Peng','Teh', 'Teoh', 'Yu', 'Yoke',
                'Tang', 'Kee', 'Sin','Chang','Teng','Soo','Xin','Meng', 'Ai', 'Lian', 'Bee', 'Chia','Jun',
                'Kuan', 'Ping','Chun','Khoo', 'Kah', 'Qi', 'Yew', 'Koh', 'Ah', 'Weng', 'Leng', 'Choon', 'Wah',
                'Tong', 'Shin', 'Lay', 'Kai', 'Foong', 'Yang', 'Cheah', 'Tai', 'Swee', 'Han', 'Hooi', 'Yeoh',
                'Jing', 'Fei', 'San', 'Loo', 'Ee', 'Toh','Sze', 'Tay', 'Sook', 'Lam', 'Su', 'Pang', 'Shu',
                'Hoon', 'Jin', 'Zhi', 'Kian', 'May', 'Hoo', 'Liang', 'Khor', 'Huat', 'Hock', 'Beng', 'Xuan',
                'Yun', 'Guan', 'Keong', 'Chung','Choong', 'Sing', 'Woon', 'Chiew', 'Keng', 'Mee', 'Jie', 'Siang',
                'Chooi', 'Ann', 'Saw', 'Chuan', 'Teo', 'Chow', 'Soh', 'Sam', 'Hua', 'Nee', 'Seow', 'Kit', 'Pui',
                'Kang', 'Yoong', 'Lan', 'Shi', 'Yuen', 'Hwa', 'Huey', 'Thong', 'Tze', 'Keat', 'Voon', 'Kin', 'En',
                'Teck', 'Man', 'Hoong', 'Wang', 'Kwan', 'Sharon', 'Yip', 'Sheng', 'Fook', 'How', 'Chu', 'Yuan',
                'Phang', 'Chuah', 'Shen', 'Chi', 'Siong', 'Kam', 'Sia', 'Kean', 'Zi', 'Yeong', 'Shan', 'Yeo',
                'Kaur', 'Loong', 'Loke', 'Ni', 'Oon', 'Koon', 'Yoon', 'Kar', 'Woo', 'Khoon', 'Theng', 'Qian', 'Er',
                'Hwee', 'Zhang', 'Fang', 'Lew', 'Fun', 'Irene', 'Tham', 'Yau', 'Tian', 'Guat', 'Sun', 'Law', 'Ken',
                'Xiao', 'Moi', 'Fatt', 'Yung', 'Hon', 'Hew', 'Mooi', 'Xian', 'Liu', 'Lye', 'Zheng', 'Koo', 'Tey',
                'Seong', 'Beh', 'Siow', 'Hin', 'Shing', 'Pin', 'Zhe', 'Chui', 'Rui', 'Onn', 'Kuen', 'Long', 'Khong',
                'Wu', 'Wing', 'Fung', 'Feng', 'Kien', 'Yean', 'Yeow', 'Khai', 'Zhen', 'Pooi', 'Jong', 'Jian', 'Haw',
                'Joo', 'Tiong', 'Choy', 'Geok', 'Hao','Liaw', 'Jen', 'Aw', 'Hung', 'Hee', 'Jenny', 'Thiam', 'Lean'},

        'Malay': {'Ahmad','Abdul','Abdullah','Zurina', 'Mohd', 'Bin', 'Binti', 'Muhammad', 'Mohamed', 'Mohamad',
              'Siti','Nurul', 'Nor', 'Mohammad', 'Ismail', 'Md', 'Ali', 'Syed', 'Noor', 'Ibrahim', 'Abd',
              'Hamba', 'Allah', 'Yusof', 'Rahman', 'Rahim', 'Azhar', 'Khan'},

    'Indian': {'Rajandran', 'Subramaniam','Kumar','Krishnan', 'Devi', 'Raja', 'Singh', 'Muniandy', 'Raman'},
    'Others': {'John', 'James', 'Emily', 'Family', 'Edward', 'Grace'},
}

def categorize_ethnic(name):
  for category, words in ethnicity_mapping.items():
    for word in name.split():
      if word in words:
        return category
  return ''

df['Ethnic'] = df['Full Name'].apply(categorize_ethnic)

# Check progress and distinct in ethnics
def check_progress():
  blank_rows = len(df[df['Ethnic'].isnull() | df['Ethnic'].eq('')])
  non_blank_rows = len(df[~df['Ethnic'].isnull() & ~df['Ethnic'].eq('')])
  total_rows = df.shape[0]
  distinct_values = df['Ethnic'].unique()

  print("Progress...")
  print(f"Total rows: {total_rows}")
  print(f"Blank rows: {blank_rows}")
  print(f"Non-blank rows: {non_blank_rows}")

  print("Distinct Item in Ethnic column: ")
  print(distinct_values)


check_progress()


# save and download the file